// TypeScript emitter.
//
// optional  ->  `email?: string`        the key may be absent
// nullable  ->  `email: string | null`  the key is always there and may hold null
// both      ->  `email?: string | null`
//
// Those three are distinct declarations and stay distinct in all four outputs.

import { jtsSortedFields, jtsMembers, jtsIsNullable, jtsIsOptional, jtsIsUnknown, jtsIsEmptyObject } from './model.js';
import { jtsJsKey } from './naming.js';

function jtsTsMemberExpr(member, ts, names) {
  switch (member) {
    case 'boolean':
      return 'boolean';
    case 'integer':
    case 'number':
      return 'number';
    case 'string':
      return 'string';
    case 'array': {
      const inner = jtsTsType(ts.array.element, names);
      // `number | string` has to be parenthesised before `[]` or it parses as
      // `number | (string[])`.
      return /[ |]/.test(inner) ? `(${inner})[]` : `${inner}[]`;
    }
    case 'object':
      return jtsIsEmptyObject(ts) ? 'Record<string, unknown>' : names.byShape.get(ts.object);
    default:
      throw new Error(`unknown member ${member}`);
  }
}

export function jtsTsType(ts, names) {
  if (jtsIsUnknown(ts)) return 'unknown';
  const parts = jtsMembers(ts).map((m) => jtsTsMemberExpr(m, ts, names));
  if (jtsIsNullable(ts)) parts.push('null');
  if (parts.length === 0) return 'unknown';
  return parts.join(' | ');
}

export function jtsEmitTypeScript(rootTs, names, opts = {}) {
  const lines = [];
  lines.push('// Generated by json-typestack. Do not edit by hand.');
  lines.push(`// Inferred from ${opts.sampleCount ?? '?'} sample(s).`);
  lines.push('');
  for (const { name, ts, shape } of names.order) {
    lines.push(`export interface ${name} {`);
    for (const f of jtsSortedFields(shape)) {
      const optional = jtsIsOptional(shape, f) ? '?' : '';
      lines.push(`  ${jtsJsKey(f.key)}${optional}: ${jtsTsType(f.type, names)};`);
    }
    lines.push('}');
    lines.push('');
  }
  if (names.order.length === 0) {
    // The root object had no fields at all.
    lines.push(`export type ${opts.rootName ?? 'Root'} = Record<string, unknown>;`);
    lines.push('');
  }
  return lines.join('\n');
}
