// Zod emitter (zod 4). Emits plain JavaScript ESM so the schema can be imported and run
// without a compile step; pair it with the TypeScript output for static types.
//
// optional  ->  .optional()   the key may be absent
// nullable  ->  .nullable()   the key is present and may hold null
// both      ->  .nullable().optional()
//
// Objects are non-strict, matching `additionalProperties: true` in the JSON Schema
// output, so both accept a sample carrying extra keys.

import { jtsSortedFields, jtsMembers, jtsIsNullable, jtsIsOptional, jtsIsUnknown, jtsIsEmptyObject } from './model.js';
import { jtsJsKey } from './naming.js';

function jtsZodMemberExpr(member, ts, names) {
  switch (member) {
    case 'boolean':
      return 'z.boolean()';
    case 'integer':
      return 'z.number().int()';
    case 'number':
      return 'z.number()';
    case 'string':
      return 'z.string()';
    case 'array':
      return `z.array(${jtsZodType(ts.array.element, names)})`;
    case 'object':
      return jtsIsEmptyObject(ts)
        ? 'z.record(z.string(), z.unknown())'
        : names.byShape.get(ts.object);
    default:
      throw new Error(`unknown member ${member}`);
  }
}

export function jtsZodType(ts, names) {
  if (jtsIsUnknown(ts)) return 'z.unknown()';
  const parts = jtsMembers(ts).map((m) => jtsZodMemberExpr(m, ts, names));
  let expr;
  if (parts.length === 0) expr = jtsIsNullable(ts) ? 'z.null()' : 'z.unknown()';
  else if (parts.length === 1) expr = parts[0];
  else expr = `z.union([${parts.join(', ')}])`;
  // z.null() already covers null; do not stack .nullable() on top of it.
  if (jtsIsNullable(ts) && parts.length > 0) expr += '.nullable()';
  return expr;
}

export function jtsEmitZod(rootTs, names, opts = {}) {
  const lines = [];
  lines.push('// Generated by json-typestack. Do not edit by hand.');
  lines.push(`// Inferred from ${opts.sampleCount ?? '?'} sample(s).`);
  lines.push('import { z } from "zod";');
  lines.push('');
  // Dependencies first: names.order is depth-first pre-order, so a parent always precedes
  // its descendants. Reversing puts every descendant before the parent that references it.
  const decls = [...names.order].reverse();
  for (const { name, shape } of decls) {
    lines.push(`export const ${name} = z.object({`);
    for (const f of jtsSortedFields(shape)) {
      let expr = jtsZodType(f.type, names);
      if (jtsIsOptional(shape, f)) expr += '.optional()';
      lines.push(`  ${jtsJsKey(f.key)}: ${expr},`);
    }
    lines.push('});');
    lines.push('');
  }
  if (decls.length === 0) {
    lines.push(`export const ${opts.rootName ?? 'Root'} = z.record(z.string(), z.unknown());`);
    lines.push('');
  }
  return lines.join('\n');
}
